apiVersion: v1
data:
  DB_HOST: ZGItc3Zj
  DB_NAME: aHA=
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_PORT: MzMwNg==
  DB_ROOT_PASSWORD: cGFzc3dvcmQ=
  DB_USER: dXNlcg==
kind: Secret
metadata:
  creationTimestamp: null
  name: db-secrets
